_target_: src.models.mnist_module.MNISTLitModule

net:
  _target_: src.models.components.simple_net.SimpleMLP
  input_size: 1024 # MNIST 被 resize 到 32x32，匹配 MLP 经典输入
  lin1_size: 256
  lin2_size: 256
  lin3_size: 256
  output_size: 10

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: src.loss.CEWithLogitsLoss
  reduction: mean

metrics:
  _target_: src.metrics.MulticlassClassificationMetric
  num_classes: 10

# compile model for faster training with pytorch 2.0
compile: false
