_target_: src.models.mnist_module.MNISTLitModule

net:
  _target_: src.models.components.simple_net.SimpleLeNet
  input_channels: 1
  input_size: 32 # MNIST 被 resize 到 32x32，匹配 LeNet 经典输入
  conv1_channels: 6
  conv2_channels: 16
  fc1_size: 120
  fc2_size: 84
  output_size: 10

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: src.loss.CEWithLogitsLoss
  reduction: mean

metrics:
  _target_: src.metrics.MulticlassClassificationMetric
  num_classes: 10

# compile model for faster training with pytorch 2.0
compile: false
